# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build
      run: go build -o exec-projmgmt-backend
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        cat >>~/.ssh/config <<END
        Host staging
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/staging.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.SERVER_USERNAME }}
        SSH_KEY: ${{ secrets.SERVER_KEY }}
        SSH_HOST: ${{ secrets.SERVER_HOST }}
    - name: Stop the server
      run: ssh staging 'ls'
    # - name: Go to directory
    #   run: ssh staging 'cd actions-runner/_work/projmgmt-backend/projmgmt-backend'
    # - name: Run
    #   run: ssh staging 'nohup ./exec-projmgmt-backend &'