# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
  CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
  CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DEMO_USER: ${{ secrets.DEMO_USER }}
  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
  EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
  GOOGLE_API_KEY_URL: ${{ secrets.GOOGLE_API_KEY_URL }}
  ORIGIN_REFERRER: ${{ secrets.ORIGIN_REFERRER }}
  PORT: ${{ secrets.PORT }}

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build
      run: go build -o exec-projmgmt-backend
    - name: Deploy
      uses: garygrossgarten/github-action-ssh@release
      with: 
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        privateKey: ${{ secrets.SERVER_KEY }}
        password: ${{ secrets.SERVER_PASSWORD }}
        command: |
          killall exec-projmgmt-backend 2>/dev/null
          cd ${{ secrets.SERVER_DIRECTORY }}
          nohup ./exec-projmgmt-backend &