# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go 1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted,instance1]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build
      run: go build -o exec-projmgmt-backend
    - name: Deploy
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        privateKey: ${{ secrets.SERVER_KEY }}
        command: |
          killall exec-projmgmt-backend 2> /dev/null
          cd ${{ secrets.SERVER_DIRECTORY }}
          nohup ./exec-projmgmt-backend &
